# Generated by Django 2.2.4 on 2020-09-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy_app', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='User',
            field=models.ForeignKey(default='idk', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip_buddy_app.User'),
            preserve_default=False,
        ),
    ]
